apiVersion: v1
kind: Service
metadata:
  name: calcul-srv
  labels:
    dev: calcul
spec:
  type: ClusterIP
  selector:
    app: calcul
  ports:
    port: 8081
    targetPort: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calcul-dep
spec:
  selector:
    matchLabels:
      app: calcul
  replicas: 3
  template:
    metadata:
      labels:
        app: calcul
    spec:
      containers:
        - name: calcul
          image: "idirall22/calcul:v1"
          resources:
            requests:
              cpu: 100Mi
          ports:
            - containerPort: 8081

      


