// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calcul

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CalculServiceClient is the client API for CalculService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculServiceClient interface {
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRes, error)
}

type calculServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculServiceClient(cc grpc.ClientConnInterface) CalculServiceClient {
	return &calculServiceClient{cc}
}

func (c *calculServiceClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddRes, error) {
	out := new(AddRes)
	err := c.cc.Invoke(ctx, "/calcul.CalculService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculServiceServer is the server API for CalculService service.
// All implementations must embed UnimplementedCalculServiceServer
// for forward compatibility
type CalculServiceServer interface {
	Add(context.Context, *AddReq) (*AddRes, error)
	mustEmbedUnimplementedCalculServiceServer()
}

// UnimplementedCalculServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalculServiceServer struct {
}

func (UnimplementedCalculServiceServer) Add(context.Context, *AddReq) (*AddRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalculServiceServer) mustEmbedUnimplementedCalculServiceServer() {}

// UnsafeCalculServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculServiceServer will
// result in compilation errors.
type UnsafeCalculServiceServer interface {
	mustEmbedUnimplementedCalculServiceServer()
}

func RegisterCalculServiceServer(s grpc.ServiceRegistrar, srv CalculServiceServer) {
	s.RegisterService(&_CalculService_serviceDesc, srv)
}

func _CalculService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calcul.CalculService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculServiceServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calcul.CalculService",
	HandlerType: (*CalculServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _CalculService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calcul.proto",
}
